### PR TITLE
DOC: Improved the docstring of Series.str.findall

### PR DESCRIPTION
**Pull request by jcontesti**
Docstring assigned to PyData Mallorca in Pandas Documentation Sprint. 

Please, any indication to improve our PR will be appreciated!

Happy to contribute :-)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Hi @jcontesti, can you open the PR directly in the pandas repo (https://github.com/pandas-dev/pandas)?

(it was in the first guidelines to do it here, but I think we changed our mind about that)

**Comment by datapythonista** [comment]
Yes, sorry about that @jcontesti, it was a last minute change. I just updated the documentation:
https://python-sprints.github.io/pandas/guide/pandas_pr.html

Thanks for the pull request, you're the first one to send it. :)

We'll give you more feedback in the pandas repo.

**Comment by jcontesti** [comment]
PR in the pandas repo done (https://github.com/pandas-dev/pandas/pull/19982).

@datapythonista BTW, the documentation still shows https://github.com/python-sprints/pandas as the repo to PR.

**Comment by datapythonista** [comment]
Good catch @jcontesti, thanks for pointing out. It should be fixed now.

**Pull request closed without merging**
